"""empty message

Revision ID: 439772657cf8
Revises: 
Create Date: 2017-04-24 07:42:11.008722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439772657cf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    # ### end Alembic commands ###
