"""empty message

Revision ID: 498053fc0948
Revises: 
Create Date: 2017-04-25 00:38:25.851190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498053fc0948'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    # ### end Alembic commands ###
